paths:
  hdf5_database_path: C:\Roy\Code\seizure-detection\seizure-detection-real-time\train_database.h5
  hdf5_database_path_2d: C:\Roy\Code\seizure-detection\seizure-detection-real-time\train_database.h5
  local_data_dir: C:\Roy\Code\seizure-detection\seizure-detection-real-time\datasets
  s3_manifest_path: C:\Roy\Code\seizure-detection\seizure-detection-real-time\s3_keep_files.txt
  target_onnx_path: C:\Roy\Code\seizure-detection\seizure-detection-real-time\seizure_detector_mobilenetv2.onnx
  parquet_dataset_path: C:\Roy\Code\seizure-detection\seizure-detection-real-time\datasets\processed_features.parquet
sampling:
  enabled: true
  negative_ratio: 2.0
  random_seed: 42
signal_processing:
  best_indices:
  - 4
  - 8
  - 19
  - 12
  - 13
  - 0
  - 1
  - 18
  - 2
  - 15
  target_hz: 128.0
  top_n_channels: 10
  window_sec: 2.0
training:
  batch_size: 64
  epochs: 5
  learning_rate: 0.001
  test_split: 0.2
  
mlflow:
  use_dagshub: false
  repo_owner: "NeuroRoy26"
  repo_name: "seizure-detection-real-time"
  experiment_name: "seizure-detection-2d-cnn"
  tracking_uri: "sqlite:///mlflow.db"
