services:
  backend:
    build: .
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - MODEL_LOCAL_PATH=seizure_detector_mobilenetv2.onnx
      - MODEL_REFRESH_SECONDS=0

  frontend:
    build: .
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000/latest
    command: streamlit run dashboard.py --server.address=0.0.0.0 --server.port=8501 --server.headless=true
    ports:
      - "8501:8501"

  streamer:
    build: .
    depends_on:
      - backend
    command: python mock_streamer.py --url http://backend:8000/ingest --hz 128.0

